server.port: 8080

application.name: TEST

spring:
  main:
    banner-mode: LOG
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
#    initialize: true
#    initialize: false
#    continue-on-error: true
#    platform: h2
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
#    hibernate:
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
#      ddl-auto: create-drop


user-service:
  url: http://localhost:8081
  endpoints:
    credentials: /api/v1/credentials
    rights: /api/v1/rights