server.port: 7979

spring:
  application.name: TEST_SERVICE
  profiles.active: default
  main.banner-mode: LOG
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    initialize: true
#    initialize: false
    continue-on-error: true
    platform: postgres
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: none
      ddl-auto: create-drop

user-service:
  url: http://localhost:8081
  endpoints:
    credentials: /api/v1/credentials
    rights: /api/v1/rights

page.default.size: 20